name: Test kapitan

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Kapitan version'
        required: true
        default: '0.30.0'
      python-version:
        description: 'Python version'
        required: true
        default: '3.9'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Setup Kapitan
        uses: humaans/setup-kapitan-action@v2.1
        with:
          version: ${{ inputs.version }}
          python-version: ${{ inputs.python-version }}
      - name: Test kapitan
        run: |
          kapitan --version
          kapitan --help
